spring:
  profiles:
    active: local
    include: oauth
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 100
#    show-sql: true

api:
  fss:
    authKey: 37cc4a0dc642205bb06d557239e72e77
    host: finlife.fss.or.kr
    bank:
      path: finlifeapi/companySearch.json
    deposit:
      path: finlifeapi/depositProductsSearch.json


--- #local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://containers-us-west-26.railway.app:6001/railway?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
      username: root
      password: kHxLwtCsXafkwjWtaJae
decorator:
  datasource:
    p6spy:
      enable-logging: true
