spring:
  main:
    web-application-type: none
  profiles:
    active: local
    include: oauth
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
  batch:
    job:
      enabled: true
      names: ${job.name:NONE}
api:
  fss:
    authKey: 37cc4a0dc642205bb06d557239e72e77
    host: finlife.fss.or.kr
    bank:
      path: finlifeapi/companySearch.json
    deposit:
      path: finlifeapi/depositProductsSearch.json
    saving:
      path: finlifeapi/savingProductsSearch.json


--- #local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/api_server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1234567
decorator:
  datasource:
    p6spy:
      enable-logging: true
logging:
  level:
    org.springframework.jdbc: debug

--- #prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mariadb://${DBHOST}:${DBPORT}/api_server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
      username: root
      password: ${DBPW}