spring:
  main:
    web-application-type: none
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 100
        format_sql: true
        default_batch_fetch_size: 100
    show-sql: true
  batch:
    job:
      name: ${job.name:NONE}
      enabled: true
    jdbc:
      initialize-schema: never
api:
  fss:
    auth-key: ${FSS_AUTH_KEY:NONE}
    base-url: https://finlife.fss.or.kr

--- #test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: 'jdbc:h2:mem:test'   # H2 DB 연결 주소 (In-Memory Mode)
    username: username        # H2 DB 접속 ID (사용자 지정)
    password: password        # H2 DB 접속 PW (사용자 지정)

  # H2 Console 설정
  h2:
    console: # H2 DB를 웹에서 관리할 수 있는 기능
      enabled: true           # H2 Console 사용 여부
      path: /h2-console       # H2 Console 접속 주소
--- #local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mariadb://localhost:3306/api_server?serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8
    username: mysqluser
    password: mysqlpw
decorator:
  datasource:
    p6spy:
      enable-logging: true
logging:
  level:
    org.springframework.jdbc: debug

--- #prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SECRET_USERNAME}
    password: ${SECRET_PASSWORD}